"""Derived-data loader. INTERACTIVE / NOT EVIDENCE.

Everything here lives in app_data/ (small, tracked, generated by
scripts/build_app_data.py from local sources). Values shown from these files
must be labeled in the UI as derived/interactive - never as frozen results.
"""

from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
APP_DATA = REPO_ROOT / "app_data"


def appdata_path(name: str) -> Path:
    return APP_DATA / name


def check_all_present() -> dict:
    expected = [
        "datasets.csv",
        "models.csv",
        "representative_series.csv",
        "forecasts_sample.csv",
        "sensitivity_compact.csv",
    ]
    return {n: appdata_path(n).exists() for n in expected}


def _read(name: str) -> pd.DataFrame:
    p = appdata_path(name)
    if not p.exists():
        return pd.DataFrame()
    return pd.read_csv(p)


def load_datasets() -> pd.DataFrame:
    return _read("datasets.csv")


def load_models() -> pd.DataFrame:
    return _read("models.csv")


def load_representative_series() -> pd.DataFrame:
    return _read("representative_series.csv")


def load_forecasts_sample() -> pd.DataFrame:
    return _read("forecasts_sample.csv")


def load_sensitivity_compact() -> pd.DataFrame:
    return _read("sensitivity_compact.csv")
