#!/usr/bin/env python
"""Full-500 SARIMA run — Store Item Demand, frozen protocol (Step 2 decision).

Identical to Notebook 07 run_sarima_subset except subset = ALL 500 Store
series (sorted, deterministic — no sampling). Same order (1,1,0)(0,1,1,7),
same pre-check, same Naive fallback (bit-for-bit), same history<origin
boundary, H=28, 8 weekly origins from 2016-03-01.

Outputs (06_results/arima/):
  sarima_store_item_full500.csv  long forecasts, model=SARIMA
  convergence_details_full500.csv  per-fit log (series x origin)
  run_log_full500.json  timing / counts / seed
all_forecasts.csv and metrics are regenerated by a follow-up step, NOT here.
"""
from __future__ import annotations

import json
import pathlib
import time
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

PROJ = pathlib.Path(__file__).resolve().parents[1]
RES = PROJ / "06_results" / "arima"
SEED = 42
H = 28
ORIGINS = [pd.Timestamp("2016-03-01") + pd.Timedelta(days=7 * k) for k in range(8)]

from statsmodels.tsa.statespace.sarimax import SARIMAX  # noqa: E402

cfg = json.load(open(PROJ / "05_experiments" / "config.json"))
cs = pd.Timestamp(cfg["common_window"]["start"])
ce = pd.Timestamp(cfg["common_window"]["end"])

print("loading store-item data ...", flush=True)
SIT_RAW = PROJ / "02_data" / "dataset_02_store_item_demand" / "raw"
sit = pd.read_csv(SIT_RAW / "train.csv", parse_dates=["date"])
sit = sit[(sit["date"] >= cs) & (sit["date"] <= ce)].copy()
sit["series_id"] = "store_" + sit["store"].astype(str) + "_item_" + sit["item"].astype(str)
dates_common = pd.date_range("2013-01-01", "2016-05-22", freq="D")
pivot = sit.pivot_table(index="date", columns="series_id", values="sales",
                        aggfunc="sum").sort_index().reindex(dates_common)
assert pivot.shape == (1238, 500), pivot.shape
subset_ids = sorted(pivot.columns.tolist())
assert len(subset_ids) == 500
print(f"series: {len(subset_ids)} (full population, deterministic sorted order)", flush=True)


def sarima_forecast(history, horizon=H, conv=None):
    if len(history) < 30 or np.all(history == 0):
        if conv is not None:
            conv.update(status="fallback_skip",
                        reason="precheck: short history / all-zero")
        return np.repeat(history[-1] if len(history) > 0 else 0, horizon)
    try:
        m = SARIMAX(history, order=(1, 1, 0), seasonal_order=(0, 1, 1, 7),
                    enforce_stationarity=False,
                    enforce_invertibility=False).fit(disp=False)
        fc = np.asarray(m.get_forecast(steps=horizon).predicted_mean, dtype=float)
        fc = np.where(np.isfinite(fc), fc, history[-1])
        fc = np.maximum(fc, 0)
        if conv is not None:
            conv.update(status="fit_ok", reason="")
        return fc
    except Exception as e:  # noqa: BLE001
        if conv is not None:
            conv.update(status="fallback_fail", reason=f"{type(e).__name__}: {e}")
        return np.repeat(float(history[-1]), horizon)


rows: list[dict] = []
conv: list[dict] = []
t0 = time.time()
for oi, od in enumerate(ORIGINS, 1):
    hist_len = int((dates_common < od).sum())
    assert dates_common[hist_len] == od, "history<origin boundary violated"
    hist_block = pivot.iloc[:hist_len]
    fut_block = pivot.iloc[hist_len:hist_len + H]
    for sid in subset_ids:
        hist = hist_block[sid].values.astype(float)
        fut = fut_block[sid].values.astype(float)
        c = {"dataset": "store_item_demand", "model": "SARIMA", "series_id": sid,
             "origin": oi, "origin_date": od, "archetype": ""}
        fc = sarima_forecast(hist, H, conv=c)
        conv.append(c)
        for h in range(H):
            rows.append({"dataset": "store_item_demand", "series_id": sid, "origin": oi,
                         "origin_date": od, "forecast_date": dates_common[hist_len + h],
                         "actual": float(fut[h]), "forecast": float(fc[h]), "model": "SARIMA"})
    print(f"origin {oi} {od.date()} done ({time.time() - t0:.0f}s elapsed)", flush=True)

df = pd.DataFrame(rows)
assert len(df) == 500 * 8 * 28, len(df)
assert df.duplicated(subset=["dataset", "series_id", "origin", "forecast_date"]).sum() == 0
df.to_csv(RES / "sarima_store_item_full500.csv", index=False)
pd.DataFrame(conv).to_csv(RES / "convergence_details_full500.csv", index=False)
log = {"seed": SEED, "n_series": 500, "n_origins": 8, "horizon": H,
       "rows": len(df), "elapsed_s": round(time.time() - t0, 1),
       "fit_ok": sum(1 for c in conv if c["status"] == "fit_ok"),
       "fallback_skip": sum(1 for c in conv if c["status"] == "fallback_skip"),
       "fallback_fail": sum(1 for c in conv if c["status"] == "fallback_fail")}
(RES / "run_log_full500.json").write_text(json.dumps(log, indent=2))
print(json.dumps(log, indent=2))
print("FULL-500 SARIMA COMPLETE")
