[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#35618A"
backgroundColor = "#F3EFE6"
secondaryBackgroundColor = "#FAF8F4"
textColor = "#1E222A"
font = "sans serif"
